export const ActionTypes = {
    OPEN_LOADER: "OPEN_LOADER",
    STOP_LOADER: "STOP_LOADER",
    STORE_POKEMON: "STORE_POKEMON",
    POKEMON_LIST: "POKEMON_LIST",
    STORE_SEARCHED_POKEMON: "STORE_SEARCHED_POKEMON"
};