export const ActionTypes = {
    OPEN_LOADER: "OPEN_LOADER",
    STOP_LOADER: "STOP_LOADER",
    STORE_POKEMON: "STORE_POKEMON",
    POKEMON_LIST: "POKEMON_LIST",
    STORE_SEARCHED_POKEMON: "STORE_SEARCHED_POKEMON",
    STORE_POKEMON_IN_MY_TEAM: "STORE_POKEMON_IN_MY_TEAM",
    REMOVE_POKEMON_FROM_MY_TEAM: "REMOVE_POKEMON_FROM_MY_TEAM",
    FETCH_MY_POKEMON: "FETCH_MY_POKEMON"
};